language: python

services:
  - docker

before_script:
  - printf "__VERSION__ = '2.0.4'\\n" >$(pwd)/lib/rpnpy/version.py
  - docker build --tag jeixav/rmnlib .

script: docker run --rm --tty jeixav/rmnlib bash -i -c 'cd python-rpn; env PYTHONPATH=$PWD/lib:$PYTHONPATH rpnpy=$PWD CMCGRIDF=$ATM_MODEL_DFILES/bcmk python -m pytest --maxfail=2'
