language: python

services:
  - docker

before_script:
  - printf "__VERSION__ = '2.0.4'\\n" >$(pwd)/lib/rpnpy/version.py
  - docker build -t jeixav/rmnlib .

script: docker run --rm -t jeixav/rmnlib bash -i -c 'cd python-rpn; env PYTHONPATH=$PWD/lib:$PYTHONPATH python -m pytest'
