language: python

services:
  - docker

before_install:
  - docker build -t jeixav/rmnlib .

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/lib
  - printf "__VERSION__ = '2.0.4'\\n" >$(pwd)/lib/rpnpy/version.py

script:
  - . .profile_armnlib
  - pytest
